[package]
name = "vst-test"
version = "0.1.0"
authors = ["mike_"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.2.0"

[lib]
name = "vsttest"
crate-type = ["cdylib"]